add healthecheck api endpoint
hoarder-app/hoarder pull request #332
Opened 2024-07-28 00:35 UTC by wuast94

Hopefully i did all right. 

Checked functionality locally.

was quite hard to find out how to disable the hooks (ESlint checking failed)

2024-07-28 00:38 UTC, wuast94 commented
will close #326

2024-09-15 01:06 UTC, MohamedBassem requested changes
Hey @wuast94, I'm really sorry it took me that long to get to this PR. Thanks a lot for taking the time to implement it. I'd understand if you no longer have time to address the requested feedback :)

2024-09-15 01:06 UTC, MohamedBassem commented on apps/web/app/api/health/route.ts
> +const checkMeilisearchHealth = async () => {
I'd keep it simple and just not check meili's health in this endpoint.

2024-09-18 06:15 UTC, wuast94 commented
> Hey @wuast94, I'm really sorry it took me that long to get to this PR. Thanks a lot for taking the time to implement it. I'd understand if you no longer have time to address the requested feedback :)

Didnt see it sry 😅 The healthcheck gets very simple then because its just the response if i didnt miss anything.

2024-09-19 10:03 UTC, MohamedBassem commented on apps/web/app/api/health/route.ts
> +    webApp: webAppStatus,
Do you mind just inlining the status in the response? Something like:
```suggestion
    status: "ok",
    message: "All good"
```

2024-09-19 10:04 UTC, MohamedBassem commented
@wuast94 yeah, the healthcheck is mostly making sure that the web server is up and running.

2024-09-19 22:12 UTC, wuast94 commented
dont know why i left the variable in there but you are right on this, good catch 😊 maybe because im not a programmer xD

2024-09-21 12:46 UTC, merged

2024-09-21 12:46 UTC, MohamedBassem commented
Thanks @wuast94!